<?php

namespace AppBundle\Repository;

/**
 * LinkingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkingRepository extends \Doctrine\ORM\EntityRepository
{
}
