AppBundle\Entity\Categories:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CategoriesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '500'
    manyToMany:
      goods:
        targetEntity: AppBundle\Entity\Goods
    lifecycleCallbacks: {  }
