AppBundle\Entity\Linking:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\LinkingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
 #   fields:
 #       categories:
 #           type: integer
  #      goods:
 #           type: integer  
    manyToOne:
        categories:
            targetEntity: Categories 
            joinColumn:
                name: categories
                referencedColumnName: id
        goods:
            targetEntity: Goods
            joinColumn:
                name: goods
                referencedColumnName: id
    lifecycleCallbacks: {  }